//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MosquitoNetRequest
    {
        public int customerId { get; set; }
        public double length { get; set; }
        public double height { get; set; }
    }
}
